name: Tests (Strict Teardown)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit & Integration
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Force prod behavior everywhere in the job
    env:
      STRICT_TEARDOWN: "1"
      PYTHONPATH: "."
      ENVIRONMENT: "prod"
      TEST_ENV: "prod"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install poetry
            poetry install
            echo "USE_POETRY=1" >> $GITHUB_ENV
          fi
          # Ensure pytest is present either way
          if [ "${USE_POETRY:-0}" = "1" ]; then
            poetry run python -m pip install pytest
          else
            python -m pip install pytest
          fi

      - name: Show CI env
        run: |
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "TEST_ENV=$TEST_ENV"

      - name: Run pytest (strict teardown)
        run: |
          if [ "${USE_POETRY:-0}" = "1" ]; then
            poetry run pytest -q --maxfail=1 --disable-warnings
          else
            pytest -q --maxfail=1 --disable-warnings
          fi
